### PR TITLE
Fix issue85

### LINKED ISSUE #85: Snooze not working in landscape
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Clock/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Clock/issues) or [closed](https://github.com/FossifyOrg/Clock/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Clock/discussions) or [closed](https://github.com/FossifyOrg/Clock/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Clock/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 8.1.0

### Affected device model

Sony Xperia L3

### How did you install the app?

Google Play Store

### Steps to reproduce the bug

1. Set an alarm
2. Turn off the screen to get full screen Alarm
3. When it goes off, rotate the device to landscape orientation, bevore you activate snooze
4. Swipe to select snooze
### Expected behavior

Snooze

### Actual behavior

If in Landscape, the alarm just gets disabled (and does not start to gi off again after the set time intervall), no matter wich option is selected. If the device is rotated back to portrait orientation, bevore seting the alarm to snooze, it works as expected.

### PR DESCRIPTION
**Pull request by Bigorthebest**
#### What is it?
- [X] Bugfix
- [ ] Feature
- [ ] Codebase improvement

#### Description of the changes in your PR

- Bug fix using the onConfigurationChanged() method to recall setupAlarmButtons() when the screen is rotated.
- The bug was caused by the binding.reminderDraggable.x value not being updated after rotation.
- Recalling setupAlarmButtons() allows the coordinates to be recalculated and fixes the issue.

#### Fixes the following issue(s)

- Fixes #85 

#### Relies on the following changes

- Needs to import android.content.res.Configuration for the onConfigurationChanged() method

#### Acknowledgement
- [X] I read the [contribution guidelines](https://github.com/FossifyOrg/Clock/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/kotlin/org/fossify/clock/activities/ReminderActivity.kt [hunk 1]
```diff
@@ -3,11 +3,14 @@ package org.fossify.clock.activities
 import android.annotation.SuppressLint
 import android.content.Context
 import android.content.Intent
+import android.content.pm.ActivityInfo
```
Comment (naveensingh) [inline app/src/main/kotlin/org/fossify/clock/activities/ReminderActivity.kt:6]: Unused import here.

File: app/src/main/kotlin/org/fossify/clock/activities/ReminderActivity.kt [hunk 2]
```diff
@@ -3,11 +3,14 @@ package org.fossify.clock.activities
...
+import android.content.res.Configuration
 import android.media.AudioManager
 import android.media.MediaPlayer
 import android.net.Uri
 import android.os.*
 import android.provider.AlarmClock
+import android.util.Log
```
Comment (naveensingh) [inline app/src/main/kotlin/org/fossify/clock/activities/ReminderActivity.kt:13]: Another unused import.

File: app/src/main/kotlin/org/fossify/clock/activities/ReminderActivity.kt [hunk 3]
```diff
@@ -224,6 +227,12 @@ class ReminderActivity : SimpleActivity() {
         }
     }
 
+    override fun onConfigurationChanged(newConfig: Configuration) {
+        super.onConfigurationChanged(newConfig)
+        setupAlarmButtons()
+    }
+
+
```
Comment (naveensingh) [inline app/src/main/kotlin/org/fossify/clock/activities/ReminderActivity.kt:235]: Multiple empty lines here, please use single empty lines.

**Comment by Bigorthebest** [comment]
Hello, I'm struggling a bit with Git, but I'm making improvements to the PR !
